repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev:  v4.3.0
  hooks:
  - id: clang-format
    args: [--style=Google]
  - id: trailing-whitespace
  - id: check-added-large-files
    args: [--maxkb=123'']

- repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.7.0
    hooks:
    - id: balck
      language_version:python3.7

- repo: https://gitlab.com/pyCQA/flake8
  rev:  5.0.4
  hooks:
  - id: flake8
