
GET_FILENAME_COMPONENT( ROOT_DIR "${PROJECT_SOURCE_DIR}" ABSOLUTE )
GET_FILENAME_COMPONENT( ROOT_SRC_DIR "${ROOT_DIR}/thinker/executor/" ABSOLUTE )
GET_FILENAME_COMPONENT( ROOT_INC_DIR "${ROOT_DIR}/thinker/executor/include/" ABSOLUTE )
GET_FILENAME_COMPONENT( ROOT_BIN_DIR "${ROOT_DIR}/bin/" ABSOLUTE )

if (NOT DEFINED THINKER_LIBRARY_OUTPUT_PATH)
GET_FILENAME_COMPONENT( ROOT_LIB_DIR "${ROOT_DIR}/lib/" ABSOLUTE )
else()
GET_FILENAME_COMPONENT( ROOT_LIB_DIR ${THINKER_LIBRARY_OUTPUT_PATH} ABSOLUTE )
endif()

SET(EXECUTABLE_OUTPUT_PATH ${BIN_DIR} )
SET(LIBRARY_OUTPUT_PATH ${LIB_DIR} )

MESSAGE( STATUS "ROOT_DIR: ${ROOT_DIR}" )
MESSAGE( STATUS "SRC_DIR: ${ROOT_SRC_DIR}" )
MESSAGE( STATUS "INC_DIR: ${ROOT_INC_DIR}" )
MESSAGE( STATUS "CMAKE_DIR: ${ROOT_CMAKE_DIR}" )
MESSAGE( STATUS "BIN_DIR: ${ROOT_BIN_DIR}" )
