name: docker
on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
             docker image build -t thinker:0.9.0 ./
             docker login -u bzcai2022 -p ${{ secrets.DOCKER_HUB_TOKEN }}
             docker push thinker:0.9.0

  # pull-docker: 
  #   needs: [build]
  #   name: pull-docker
  #   runs-on: self-hosted
  #   steps:
  #     - name: Deploy
  #       uses: appleboy/ssh-action@main
  #       with:
  #           host: ${{ secrets.HOST }} 
  #           username: ${{ secrets.HOST_USERNAME }} 
  #           password: ${{ secrets.HOST_PASSWORD }} 
  #           port: ${{ secrets.HOST_PORT }} 
