name: linux
on:
  push:
    branches:
     - main
     - 'thinker/**'
    paths:
      - 'thinker/**'
      - 'thinker/executor/**'
      - '.github/workflows/linux_x86.yml'
  pull_request:
    branches: [main]
    paths:
      - 'thinker/**'
      - 'test/**'
      - '.github/workflows/linux_x86.yml'

concurrency:
  group: linux-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  get_path:
    runs-on:  self-hosted
    steps:
      - name: display the path
        run:  echo  $PATH
        shell:  bash

  linux_build_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - echo: "build begin"
      - name: build
        run: |
            conda create -n thinker-env python==3.8.5
            conda activate thinker-env
            pip install -U pip
            cat requirements.txt | xargs -n 1 pip install
      - echo: "build end"
      - name: test
        run: sh ./test/auto_test.sh
