name: linux
on:
  push:
    branches:
     - main
     - 'thinker/**'
    paths:
      - 'thinker/**'
      - 'thinker/executor/**'
      - '.github/workflows/linux_x86.yml'
  pull_request:
    branches: [main]
    paths:
      - 'thinker/**'
      - 'test/**'
      - '.github/workflows/linux_x86.yml'

concurrency:
  group: linux-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  linux_build_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: begin
        run:  echo 'config env start'
      - name: build
        run: |
            conda activate thinker-env

      - name: end
        run:  echo  'config env complete'
      - name: test
        run: sh ./test/auto_test.sh
