name: linux
on:
  push:
    branches:
     - master
     - 'feature/**'
    paths:
      - 'thinker/executor/**'
      - '.github/workflows/linux.yml'
  pull_request:
    branches: [master]
    paths:
      - 'thinker/**'
      - 'test/**'
      - '.github/workflows/linux_x86.yml'

concurrency:
  group: linux-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  linux_build_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
            conda create -n thinker-env python==3.8.5
            conda activate thinker-env
            pip install -U pip
            cat requirements.txt | xargs -n 1 pip install

      - name: test
        run: sh ./test/auto_test.sh
