name: linux
on:
  push:
    branches:
     - main
     - 'thinker/**'
    paths:
      - 'thinker/**'
      - 'thinker/executor/**'
      - '.github/workflows/linux_x86.yml'

concurrency:
  group: linux-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  linux_build_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: build
        run:  conda activate thinker-env
  x86_linux_test:
    needs:  linux_build_test
    runs-on: self-hosted
    steps:
      - name: test
        run:  ./test/auto_test.sh
