name:  Docker Image CI/CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
         run: |
              docker image build -t thinker:0.9.0 ..
              docker login -u bzcai2022 -p ${{ secrets.DOCKER_HUB_TOKEN }}
              docker push thinker:0.9.0


