name: Build and Publish Docker Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Log into Docker Hub
         run: docker login -u bzcai2022 -p ${{ secrets.DOCKER_HUB_TOKEN }}



