name: Build and Publish Docker Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
         run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:0.1.0 ./
      - name: Log into Docker Hub
         run: docker login -u bzcai2022 -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Push Image 
         run: docker push ${{ secrets.DOCKER_REPOSITORY }}:0.1.0


