name: test
on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  linux_build_test:
    # runs-on: ubuntu
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: build
        run:  |
              echo "build"
              wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh
              bash Anaconda3-5.0.1-Linux-x86_64.sh -b
              
