name: linux
on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  linux_build_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: build
        run:  echo "build"
